-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Feb 20, 2018 at 20:30 PM
-- Server version: 5.6.26
-- PHP Version: 5.6.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cdac_ems`
--

DROP TABLE IF EXISTS `job_offers`;

-- --------------------------------------------------------

--
-- Table structure for table `job_offers`
--

CREATE TABLE IF NOT EXISTS `job_offers` (
  `offer_id` bigint(20) NOT NULL,
  `candicate_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Candidatecode generated by system',
  `job_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Deparments Job Code FK from job_postings',
  `department_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Deparment for which the Job is posted FK from ems_departments master',
  `branch_code` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Job offer location. which branch of the department',
  `offer_start_dt` date NOT NULL COMMENT 'Date on which the offer ',
  `offer_end_dt` date NOT NULL COMMENT 'Date till which the Offer Letter is valid ',
  `reporting_dt` date NOT NULL COMMENT 'Date on which candicate has to report for joining',
  `joining_dt` date NOT NULL COMMENT 'Date on which candicate has joined',
  `offered_salary` DECIMAL(13,2) NOT NULL COMMENT 'Gross Salary ofered',
  `offer_status` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Can be DRAFT, SENT, ACCEPTED, REJECTED, JOINED',
  `status` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Record status Active, Inactive or Deleted',
  `created_by` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `created_dt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `modified_dt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `job_offers`
--
ALTER TABLE `job_offers`
  ADD PRIMARY KEY (`offer_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `job_offers`
--
ALTER TABLE `job_offers`
  MODIFY `row_id` bigint(20) NOT NULL AUTO_INCREMENT;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `job_offers`
--
ALTER TABLE `job_offers`
  ADD CONSTRAINT `job_offers_ibfk_1` FOREIGN KEY (`candicate_code`) REFERENCES `job_interview_registrations` (`candicate_code`),
  ADD CONSTRAINT `job_offers_ibfk_2` FOREIGN KEY (`job_code`) REFERENCES `job_postings` (`job_code`)
  ADD CONSTRAINT `job_offers_ibfk_3` FOREIGN KEY (`department_code`) REFERENCES `ems_departments` (`department_code`),
  ADD CONSTRAINT `job_offers_ibfk_4` FOREIGN KEY (`branch_code`) REFERENCES `ems_department_branches` (`branch_code`);
